# Generated by Django 4.1.6 on 2023-08-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
