# Generated by Django 3.2.4 on 2022-05-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
