# Generated by Django 3.2.4 on 2022-05-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='ContactForm',
        ),
    ]
