# Generated by Django 4.1.6 on 2023-08-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_in_private_flan_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='image_url',
            new_name='image',
        ),
    ]
